---
title: "p8105_hw6_zl3118"
author: "Shirley Liang"
date: "2022-11-28"
output: github_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(rnoaa)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)

```

```{r, Probelm 1}

weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())

boot_sample = function(df) {
  sample_frac(df, replace = TRUE)}
  
bootstrapping = 
  tibble(
    strap_number = 1:5000,
    strap_sample = rerun(5000, boot_sample(weather_df))
  )

bootstrap_results_r = 
  bootstrapping %>% 
  mutate(
    models = map(strap_sample, ~lm(tmax~tmin, data = .x)), 
    results1 = map(models, broom::glance)
  ) %>%
  select(-strap_sample, -models) %>% 
  unnest(results1)
bootstrap_results_r %>% 
  ggplot(aes(x = r.squared)) + geom_density()

```

The distribution is approximately normal and slightly skew to the left. 

```{r, problem 1 cont.}

bootstrap_results_beta = 
  bootstrapping %>% 
  mutate(
    models = map(strap_sample, ~lm(tmax ~ tmin, data = .x)),
    results2 = map(models, broom::tidy)
  ) %>% 
  select(-strap_sample, -models) %>% 
  unnest(results2)

bootstrap_results_log = 
  bootstrap_results_beta %>% 
  select(strap_number, term, estimate) %>% 
  pivot_wider(
    names_from = term, 
    values_from = estimate
  ) %>% 
  mutate(log = log(`(Intercept)`*`tmin`))
ggplot(bootstrap_results_log, aes(x = log)) + geom_density()

```
The distribution is also approximately normal, a little tail extending to lower values, which indicates there might be large outliers included. 

```{r}

bootstrap_results_r %>% 
  summarise(
    ci_lower = quantile(r.squared, 0.025),
    ci_upper = quantile(r.squared, 0.975)
  ) %>% 
  knitr::kable()
bootstrap_results_log %>% 
  summarise(
    ci_lower = quantile(log, 0.025), 
    ci_upper = quantile(log, 0.975)
  ) %>% 
  knitr::kable()

```
The 95% confidence intervals are `(0.8940, 0.9274)` and `(1.9657,2.0586)` for `r-squared` and `log(beta0*beta1)`, respectively. 


```{r, question 2}

homicides = read_csv("./homicide-data.csv")
homicides_clean = homicides %>% 
  janitor::clean_names() %>% 
  mutate(city_state = str_c(city, state, sep = "_")) %>% 
  filter(!city_state %in% c("Dallas_TX", "Phoenix_AZ", "Kansas City_MO", "Tulsa_AL"), 
         victim_race %in% c("Black", "White")) %>% 
  mutate(victim_age = as.numeric(victim_age),
         resolved = as.numeric(disposition == "Closed by arrest"),
         victim_race = fct_relevel(victim_race, "White"),
         victim_sex = fct_relevel(victim_sex, "Female"))

baltimore_glm = homicides_clean %>% 
  filter(city_state == "Baltimore_MD") %>% 
  glm(resolved ~ victim_age + victim_sex + victim_race, family = binomial(), data = .) %>% 
  broom::tidy()

baltimore_glm

baltimore_OR = baltimore_glm %>% 
  mutate(OR = exp(estimate),
         CI_lower = exp(estimate - 1.96 * std.error),
         CI_upper = exp(estimate + 1.96 * std.error))

baltimore_OR %>%
  filter(term == "victim_sexMale") %>%
  select(term, OR, CI_lower, CI_upper) %>% 
  knitr::kable(digits = 2)

```

```{r}



```

